[package]
name = "harp"
version = "0.1.0"
edition = "2021"
description = """
Integration of R and Rust.
"""

[dependencies]
libR-sys = "0.3.0"
log = "0.4.17"
stdext = { path = "../stdext" }
thiserror = "1.0.37"
walkdir = "2.3.2"
