blank_issues_enabled: false
contact_links:
  - name: Questions and feedback
    url: https://github.com/posit-dev/positron/discussions
    about: Ask questions and share your feedback with the team.

