blank_issues_enabled: false
contact_links:
  - name: Questions and Feedback
    url: https://app.slack.com/client/T02V9CHFH/C05M2EZCPGR
    about: Please ask questions and share your feedback with the team.

