[package]
name = "harp"
version = "0.1.0"
edition = "2021"
description = """
Tools for integrating R and Rust.
"""

[dependencies]
ctor = "0.1.26"
harp-macros = { path = "./harp-macros" }
lazy_static = "1.4.0"
libR-sys = "0.4.0"
log = "0.4.17"
stdext = { path = "../stdext" }

[target.'cfg(all(target_os="linux", target_arch="aarch64"))'.dependencies]
libR-sys = { version = "0.4.0", features = ["use-bindgen"] }

