name: "Positron: Push Beta Release"
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag, e.g. '2024.03.0-1095'"
        required: true
        type: string

env:
  RELEASE_TAG: ${{ inputs.release_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Download Windows Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          version: tags/${{ env.RELEASE_TAG }}
          file: Positron-${{ env.RELEASE_TAG }}-Setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download MacOS Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          version: tags/${{ env.RELEASE_TAG }}
          file: Positron-${{ env.RELEASE_TAG }}.dmg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Debian Linux Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          version: tags/${{ env.RELEASE_TAG }}
          file: Positron-${{ env.RELEASE_TAG }}.deb
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create access token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.POSITRON_BOT_APP_ID }}
          private-key: ${{ secrets.POSITRON_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create Release to Private Beta
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: posit-dev/positron-beta
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: false
          body: |
            ### Positron ${{ env.RELEASE_TAG }} (Beta)

            Thank you for helping test Positron!

            Positron is currently in Private Beta.

            To download Positron, go to **Assets** and select the `.dmg` for Mac (Universal), `.exe` for Windows x64 (System), or `.deb` for Debian-based Linux (Ubuntu).

            Releases are made available under the terms of the [Software Evaluation License](https://github.com/posit-dev/positron?tab=License-1-ov-file) from [Posit Software, PBC](https://posit.co/).

            > [!NOTE]
            > Assets `Source code (zip)` and `Source code (tar.gz)` are generated by GitHub and only contain a snapshot of the license and third-party notices from this repository.
          files: |
            Positron-${{ env.RELEASE_TAG }}-Setup.exe
            Positron-${{ env.RELEASE_TAG }}.dmg
            Positron-${{ env.RELEASE_TAG }}.deb
