name: Build macOS Release

on: workflow_dispatch

jobs:
  macos:
    name: Build macOS Release
    runs-on: [self-hosted, macos, arm64]
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Fetch full history; required so we can determine the build version with rev-list
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Node 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Perform initial (arm64) dependency download/install
      - name: Install Dependencies (arm64)
        run: yarn

      # Build client for arm64
      - name: Build Client (arm64)
        run: yarn gulp vscode-darwin-arm64

      # Remove arm64 node_modules folders so we can rebuild for x64
      - name: Clean Client (arm64)
        run: git ls-files --directory -i -o -x node_modules | xargs rm -rf

      # Reinstall node_modules binaries for x64
      - name: Install Dependencies (x64)
        env:
          npm_config_arch: x64
        run: yarn

      # Build client for x64
      - name: Build Client (x64)
        run: yarn gulp vscode-darwin-x64

      # Glue together the arm64 and x64 binaries with lipo to create a
      # universal build
      - name: Create universal build
        env:
           VSCODE_ARCH: universal
           DEBUG: "*"
           AGENT_BUILDDIRECTORY: ".."
        run: node build/darwin/create-universal-app.js

      - name: Run Unit Tests
        id: electron-unit-tests
        run: DISPLAY=:10 ./scripts/test.sh

      - name: Run Integration Tests (Electron)
        id: electron-integration-tests
        run: DISPLAY=:10 ./scripts/test-integration.sh

