name: "Positron: Push Beta Release"
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag, e.g. '2024.03.0-1085'"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Download Windows Release Asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ inputs.release_tag }}
          file: Positron-${{ inputs.release_tag }}-Setup.exe
          target: ./
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download MacOS Release Asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ inputs.release_tag }}
          file: Positron-${{ inputs.release_tag }}.dmg
          target: ./
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release to Private Beta
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.POSITRON_GITHUB_PAT }}
          repository: posit-dev/positron-temp
          tag_name: ${{ inputs.release_tag }}
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: false
          body: |
            Positron ${{ inputs.release_tag }} (Beta)

            Thank you for helping test Positron!

            Positron is currently in Private Beta.

            To download Positron, click on Assets and select the .dmg for Mac (Universal) or
            .exe for Windows x64 (System).

            Releases are made available under the terms of the Software Evaluation License from
            Posit Software, PBC.

            __Assets Source code (zip) and Source code (tar.gz) are generated by GitHub and only
            contain a snapshot of the license and third-party notices from this repository.__
          files: |
            "Positron-${{ inputs.release_tag }}-Setup.exe"
            "Positron-${{ inputs.release_tag }}.dmg"
