
# These are speculative; we can update as appropriate.
# Multiple items are commented out below as they are available only with Rust nightly.

# binop_separator = "Back"
# format_macro_matchers = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Item"
match_block_trailing_comma = true
max_width = 100
# normalize_comments = true
# overflow_delimited_expr = true
reorder_imports = true
reorder_modules = true

