# These are speculative; we can update as appropriate.
binop_separator = "Back"
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
match_block_trailing_comma = true
normalize_comments = true
overflow_delimited_expr = true
